// <auto-generated />
using HIC.WebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HIC.WebAPI.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("HIC.WebAPI.Domain.Models.InventoryBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 25,
                            Description = "Ordered from Wayfair",
                            Name = "Table"
                        },
                        new
                        {
                            Id = 2,
                            Count = 49,
                            Description = "Delivered by Amazon",
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 3,
                            Count = 17,
                            Description = "Extra stock",
                            Name = "Vases"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
